### ISSUE TITLE
FTGooglePlacesAPIDetailResponse.h:88:41: Unknown type name 'CGFloat'

### ISSUE THREAD

**Issue by Ricardo1980** [manGoweb/FTGooglePlacesAPI#15]
I receive these 2 errors (I use cocoapods, Version 6.3.1):

/src/Pods/Headers/Public/FTGooglePlacesAPI/FTGooglePlacesAPIDetailResponse.h:88:41: Unknown type name 'CGFloat'

src/Pods/Headers/Public/FTGooglePlacesAPI/FTGooglePlacesAPISearchResultItem.h:55:41: Unknown type name 'CGFloat'

In this line:
@property (nonatomic, assign, readonly) CGFloat rating;

Any idea? Maybe it's related to the new xcode version.

**Comment by rafiki270** [comment]
did you import uikit? this is usually problem of missing basic frameworks

> On 5 May 2015, at 16:26, Ricardo Ruiz notifications@github.com wrote:
> 
> I receive these 2 errors (I use cocoapods):
> 
> /src/Pods/Headers/Public/FTGooglePlacesAPI/FTGooglePlacesAPIDetailResponse.h:88:41: Unknown type name 'CGFloat'
> 
> src/Pods/Headers/Public/FTGooglePlacesAPI/FTGooglePlacesAPISearchResultItem.h:55:41: Unknown type name 'CGFloat'
> 
> In this line:
> @property https://github.com/property (nonatomic, assign, readonly) CGFloat rating;
> 
> Any idea?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/FuerteInternational/FTGooglePlacesAPI/issues/15.

## 

_-----------------------------------------------_

_Confidentiality notice_

This communication is from Fuerte Int Ltd, a private limited company 
registered in England and Wales with registered number 07266175 having its 
registered office at THE MANOR HOUSE, 34 LONDON ROAD, NEWBURY, BERKSHIRE, 
ENGLAND, RG14 1JX . 

This electronic message contains information which may be privileged and 
confidential. The information is intended to be for the use of the 
individual(s) or entity named above. If you are not the intended recipient 
be aware that any disclosure, copying, distribution or use of the contents 
of this information is prohibited. If you have received this electronic 
message in error, please notify us by telephone or e-mail as above 
immediately.

**Comment by Ricardo1980** [comment]
Where exactly?
I added it to my frameworks (in my project) and still nothing.

**Comment by rafiki270** [comment]
This is the first time we hear about this, please Google following:
https://www.google.com/webhp?hl=en#hl=en&q=Unknown+type+name+%27CGFloat%27

> On 5 May 2015, at 16:38, Ricardo Ruiz notifications@github.com wrote:
> 
> Where exactly?
> I added it to my frameworks (in my project) and still nothing.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/FuerteInternational/FTGooglePlacesAPI/issues/15#issuecomment-99119435.

## 

_-----------------------------------------------_

_Confidentiality notice_

This communication is from Fuerte Int Ltd, a private limited company 
registered in England and Wales with registered number 07266175 having its 
registered office at THE MANOR HOUSE, 34 LONDON ROAD, NEWBURY, BERKSHIRE, 
ENGLAND, RG14 1JX . 

This electronic message contains information which may be privileged and 
confidential. The information is intended to be for the use of the 
individual(s) or entity named above. If you are not the intended recipient 
be aware that any disclosure, copying, distribution or use of the contents 
of this information is prohibited. If you have received this electronic 
message in error, please notify us by telephone or e-mail as above 
immediately.

**Comment by Ricardo1980** [comment]
Thanks  a lot @rafiki270 !
I added
#import <UIKit/UIKit.h>
#import "FTGooglePlacesAPI.h"

And now works!
